---
server:
  port: 3301
spring:
  profiles: dev
  application:
    name: springcloud-config-server
---
server:
  port: 3302
spring:
  profiles: test
  application:
    name: springcloud-config-server
